"""Pydantic schemas for report generation."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class ReportRequest(BaseModel):
    analysis_id: str


class ReportSection(BaseModel):
    title: str
    content: str


class ReportResponse(BaseModel):
    report_id: str
    analysis_id: str
    generated_at: str
    sections: list[ReportSection] = Field(default_factory=list)
    summary: str = ""
    disclaimer: str = (
        "This report is generated by an AI-assisted recommendation system. "
        "All recommendations require human verification against official BIS records. "
        "AI relevance scores do not constitute legal applicability."
    )
